### ISSUE TITLE
Implicite Differentiation

### ISSUE THREAD

**Issue by BolinPan** [IndigoPurple/DEQSCI#1]
By any reason you decided not to use the implicit differentiation in the backward pass under the class DEQFixedPointADMM?

**Comment by IndigoPurple** [comment]
> By any reason you decided not to use the implicit differentiation in the backward pass under the class DEQFixedPointADMM?

As we have discussed in our emails and meetings, due to time constraints in preparing the paper, the current work has not implemented ADMM. Future work will continue to explore this approach.
